// Generated by CoffeeScript 1.6.1
(function() {

  jQuery(function() {
    jQuery("#help").click(function(event) {
      return jQuery(this).fadeOut(event);
    });
    jQuery(window).scroll(function() {
      return jQuery('#results').css({
        left: $(this).scrollLeft()
      });
    });
    return window.setTimeout((function() {
      return jQuery("#help").fadeOut();
    }), 15000);
  });

}).call(this);
