// Generated by CoffeeScript 1.6.1

/*
Folk Tune Finder tune explorer!

The bit that just does searches and displays them and stuff.

Copyright Joe Wass 2011 - 2013
joe@afandian.com
*/


(function() {
  var Searcher,
    _this = this;

  Searcher = (function() {

    function Searcher(resultsElement, apiUrl, imageUrl, tuneUrl) {
      var _this = this;
      this.resultsElement = resultsElement;
      this.apiUrl = apiUrl;
      this.imageUrl = imageUrl;
      this.tuneUrl = tuneUrl;
      this.queryString = function(path) {
        return Searcher.prototype.queryString.apply(_this, arguments);
      };
      this.search = function(event, path) {
        return Searcher.prototype.search.apply(_this, arguments);
      };
      jQuery("body").bind("searchPathChanged", this.search);
    }

    Searcher.prototype.search = function(event, path) {
      var args, query,
        _this = this;
      query = this.queryString(path);
      args = {
        url: query,
        dataType: 'jsonp',
        success: function(data) {
          var docId, ends, imageUrl, li, result, results, selectionRange, starts, title, tuneUrl, urlWithSelection, _i, _j, _len, _ref, _results, _results1;
          $("#number").text(data.TotalFound);
          results = $("#result-list");
          results.empty();
          _ref = data.Results;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            result = _ref[_i];
            docId = result.DocumentId;
            starts = result.Starts;
            ends = result.Ends;
            selectionRange = (function() {
              _results1 = [];
              for (var _j = starts; starts <= ends ? _j <= ends : _j >= ends; starts <= ends ? _j++ : _j--){ _results1.push(_j); }
              return _results1;
            }).apply(this).join(":");
            title = result.Title.join(" / ");
            imageUrl = _this.imageUrl + docId + "/";
            urlWithSelection = imageUrl + selectionRange + "/";
            tuneUrl = _this.tuneUrl + docId + "/";
            li = $("<li></li>");
            li.append($("<a>", {
              href: tuneUrl
            }).text(title).append($("<img>", {
              src: urlWithSelection,
              alt: title,
              "class": "selection"
            })));
            _results.push(results.append(li));
          }
          return _results;
        }
      };
      return jQuery.ajax(args);
    };

    Searcher.prototype.queryString = function(path) {
      var params;
      params = {
        melody: path.join(",")
      };
      return this.apiUrl + "?" + jQuery.param(params);
    };

    return Searcher;

  })();

  jQuery(function() {
    var API_URL, INCIPIT_IMAGE_BASE, TUNE_URL, searchResultsElement, searcher;
    searchResultsElement = jQuery("#results");
    API_URL = "http://api-cache.folktunefinder.com/search/";
    INCIPIT_IMAGE_BASE = "http://cache.folktunefinder.com/typeset/dots/incipit/";
    TUNE_URL = "http://folktunefinder.com/tune/";
    return searcher = Searcher(searchResultsElement, API_URL, INCIPIT_IMAGE_BASE, TUNE_URL);
  });

}).call(this);
