// Generated by CoffeeScript 1.6.1

/*
Folk Tune Finder tune explorer!

The bit that just does searches and displays them and stuff.

Copyright Joe Wass 2011 - 2013
joe@afandian.com
*/


(function() {
  var Searcher,
    _this = this;

  Searcher = (function() {

    function Searcher(resultsElement, apiUrl) {
      var _this = this;
      this.resultsElement = resultsElement;
      this.apiUrl = apiUrl;
      this.queryString = function(path) {
        return Searcher.prototype.queryString.apply(_this, arguments);
      };
      this.search = function(event, path) {
        return Searcher.prototype.search.apply(_this, arguments);
      };
      jQuery("body").bind("searchPathChanged", this.search);
    }

    Searcher.prototype.search = function(event, path) {
      var args, query;
      query = this.queryString(path);
      args = {
        url: query,
        dataType: 'jsonp',
        success: function(data) {
          return console.log(data);
        }
      };
      return jQuery.ajax(args, function(data) {
        return console.log(data);
      });
    };

    Searcher.prototype.queryString = function(path) {
      var params;
      params = {
        melody: path.join(",")
      };
      return this.apiUrl + "?" + jQuery.param(params);
    };

    return Searcher;

  })();

  jQuery(function() {
    var API_URL, searchResultsElement, searcher;
    searchResultsElement = document.getElementById("results");
    API_URL = "http://api-cache.folktunefinder.com/search/";
    API_URL = "http://folktunefinder.com:8080/search/";
    return searcher = Searcher(searchResultsElement, API_URL);
  });

}).call(this);
